import { ClerkProvider } from '@clerk/nextjs';
import { jaJP } from '@clerk/localizations';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/providers/query-provider';
import SheetProvider from '@/providers/sheet-provider';
import { Toaster } from '@/components/ui/sonner';
import IgnoreConsoleError from './ignore-console-error';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={jaJP}>
      <html lang="ja">
        <body className={inter.className}>
          <QueryProvider>
            <SheetProvider />
            <main>{children}</main>
            <Toaster />
            <IgnoreConsoleError />
          </QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
