import { ClerkProvider } from '@clerk/nextjs';
import { jaJP } from '@clerk/localizations';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { QueryProvider } from '@/providers/query-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={jaJP}>
      <html lang="ja">
        <QueryProvider>
          <body className={inter.className}>{children}</body>
        </QueryProvider>
      </html>
    </ClerkProvider>
  );
}
